apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.10.1
    chart: longhorn
    helm:
      valuesObject: # using this instead of the values.yaml file since the file was not working
        defaultSettings:
          allowCollectingLonghornUsageMetrics: false
          defaultDataPath: /var/mnt/longhorn
          storageReservedPercentageForDefaultDisk: 0
        preUpgradeChecker:
          jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
    syncOptions:
      - CreateNamespace=true
