apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-root-ca
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/hook: PostSync
spec:
  secretName: selfsigned-root-ca
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
  isCA: true
  subject:
    countries:
      - usa
    organizations:
      - hunt
  commonName: selfsigned-root-ca
  duration: 87600h # 10 years * 365 days * 24 hours
  renewBefore: 4320h # 6 months before it ends. 180 days * 24 hours
