apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        annotations:
          lbipam.cilium.io/ips: "192.168.30.80"
  logging:
    level:
      default: debug
  telemetry:
    accessLog:
      disable: false
